name: Sync Fork

on:
  schedule:
    - cron: '20 */8 * * *' # every 8 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: kongspark
          base: beta
          head: beta
